### ISSUE TITLE
SignalR problem with SkipNegotiation = true

### ISSUE THREAD

**Issue by iserofeev** [Benedicht/BestHTTP-Issues#200]
Hello,

After updating to version 2, we faced a SignalR problem when using only WebSockets as transport.

We successfully fixed it by editing the source code of **HubConnection.cs**.

<img width="986" alt="Screenshot 2024-07-18 at 11 48 35" src="https://github.com/user-attachments/assets/93bf9228-ecae-4cfd-9eef-1d36fab712f7">

The core of the problem is a null reference of **NegotiationResult**. It is called after the connection, but it is set only if **SkipNegotiation** is false (which is the default).

Setting **NegotiationResult** fixes this problem. I hope you will address this in your source code in future updates.

Thanks for a great asset!

**Comment by Benedicht** [comment]
Thanks for the report, fixed in the next version!

**Comment by iserofeev** [comment]
Hello, I've just updated to the latest version, but I'm still seeing this problem. I hope it will be fixed in future releases, and I'd appreciate knowing in which version it will be addressed.

**Comment by Benedicht** [comment]
I couldn't replicate it with the latest version. It was included in v3.0.3, released on 09-09.
